name: news_shelf
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  args: ^2.0.0


#  server
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_swagger_ui: ^1.0.0+2

#  state management
  riverpod: ^1.0.3

# code gen
  json_serializable: ^6.3.1
  equatable: ^2.0.3
  retrofit: any
  logger: any
  json_annotation: any

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0

  #code gen
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  json_annotation: ^4.6.0
