openapi: 3.0.0
info:
  description: "API system"
  version: "1.0.10"
  title: "Swagger Test"
servers:
  - url: http://newsshelf.serubii.com
    description: News API
tags:
  - name: "test"
    description: "News Access"
